export const CHANGE_NAME = 'CHANGE_NAME';
export const MOUSE_HOVER_COMPETITOR_CARD = 'MOUSE_HOVER_COMPETITOR_CARD';
export const MOUSE_LEAVE_COMPETITOR_CARD = 'MOUSE_LEAVE_COMPETITOR_CARD';
export const CHANGE_SCORE = 'CHANGE_SCORE';
export const START_MATCH = 'START_MATCH';
export const RESTART_COMPETITION = 'RESTART_COMPETITION';